fix: move pipeline to correct folder

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,9 +2,14 @@ name: IoT Dashboard DevSecOps Pipeline
 
 on:
   push:
-    branches: [ master, develop ]
+    branches:
+      - master
+      - develop
+      - 'feature/**'
   pull_request:
-    branches: [ master, develop ]
+    branches:
+      - master
+      - develop
   workflow_dispatch:
 
 jobs:
@@ -23,7 +28,89 @@ jobs:
     - name: Install Dependencies
       run: |
         pip install -r requirements.txt
-
     - name: Check Code (Syntax Test)
       run: |
         python -m py_compile Arms.py
+      # 🔍 SAST - CodeQL
+  sast:
+    name: SAST - CodeQL
+    runs-on: ubuntu-latest
+    needs: build
+
+    permissions:
+      security-events: write
+      actions: read
+      contents: read
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: python
+
+      - name: Autobuild
+        uses: github/codeql-action/autobuild@v3
+
+      - name: Analyze Code
+        uses: github/codeql-action/analyze@v3
+
+
+  # 🌐 DAST - OWASP ZAP
+  dast:
+    name: DAST - OWASP ZAP
+    runs-on: ubuntu-latest
+    needs: sast
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install Dependencies
+        run: pip install -r requirements.txt || true
+
+      - name: Start Flask App
+        run: |
+          python Arms.py &
+          sleep 10
+      - name: Run ZAP Scan
+        uses: zaproxy/action-baseline@v0.11.0
+        with:
+          target: 'http://localhost:5000'
+          fail_action: false   # 🔥 pipeline fails if vulnerabilities found
+
+
+  # 🚀 DEPLOY TO EC2
+  deploy:
+    name: Deploy to EC2 (Docker)
+    runs-on: ubuntu-latest
+    needs: [sast, dast]
+    steps:
+      - name: Deploy via SSH
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          key: ${{ secrets.EC2_KEY }}
+          script: |
+            # Go to project (clone if first time)
+            if [ ! -d "Flask-IoT-Dashboard" ]; then
+              git clone https://github.com/${{ github.repository }}.git
+            fi
+            cd Flask-IoT-Dashboard
+            # Pull latest code
+            git pull origin master
+            docker stop flask-app || true
+            docker rm flask-app || true
+            # Build new image
+            docker build -t flask-iot .
+            # Run new container
+            docker run -d -p 5000:5000 --name flask-app flask-iot            # Stop old container (if exists)
+          username: ${{ secrets.EC2_USER }}
+
